### ISSUE TITLE
[BUG] Line feed causes crash while kanjionly is false

### ISSUE THREAD

**Issue by iamllama** [Kuuuube/kanjigrid#8]
When `kanjionly` is false, a line feed (0xA) causes kanjigrid to crash.

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1610304449\__init__.py", line 396, in setup
    self.makegrid(config)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1610304449\__init__.py", line 270, in makegrid
    self.displaygrid(config, deckname, units)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1610304449\__init__.py", line 188, in displaygrid
    self.generate(config, units)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1610304449\__init__.py", line 122, in generate
    table += kanjitile(unit.value, bgcolor, total_count, unit.avg_interval)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1610304449\__init__.py", line 41, in kanjitile
    tooltip = "Character: %s" % unicodedata.name(char)
ValueError: no such name
```

On my system and on wsl (python 3.13), `unicodedata.name` throws when passed any char less than 0x20, i.e all the ascii control chars 🤔

Not particularly serious, but linefeed shows up as an innocuous blank line so it might be hard to catch otherwise

**Comment by Kuuuube** [comment]
Fixed with [61aab24](https://github.com/Kuuuube/kanjigrid/commit/61aab24fa3c62bdcb994e7c41027c8028c79d78b)
